//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.05 at 01:26:51 PM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.certificateservices.messages.csmessages.jaxb.CSRequest;


/**
 * <p>Java class for BaseRegisterRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseRegisterRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSRequest">
 *       &lt;sequence>
 *         &lt;element name="itsId" type="{http://certificateservices.org/xsd/v2x_2_0}ItsIdType"/>
 *         &lt;element name="ecProfile" type="{http://certificateservices.org/xsd/v2x_2_0}ProfileNameType" minOccurs="0"/>
 *         &lt;element name="atProfile" type="{http://certificateservices.org/xsd/v2x_2_0}ProfileNameType" minOccurs="0"/>
 *         &lt;element name="itsValidFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="itsValidTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="regions" type="{http://certificateservices.org/xsd/v2x_2_0}RegionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseRegisterRequestType", propOrder = {
    "itsId",
    "ecProfile",
    "atProfile",
    "itsValidFrom",
    "itsValidTo",
    "regions"
})
@XmlSeeAlso({
    UpdateITSRequest.class,
    RegisterITSRequest.class
})
public class BaseRegisterRequestType
    extends CSRequest
{

    @XmlElement(required = true)
    protected String itsId;
    protected String ecProfile;
    protected String atProfile;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itsValidFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itsValidTo;
    protected RegionsType regions;

    /**
     * Gets the value of the itsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItsId() {
        return itsId;
    }

    /**
     * Sets the value of the itsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItsId(String value) {
        this.itsId = value;
    }

    /**
     * Gets the value of the ecProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcProfile() {
        return ecProfile;
    }

    /**
     * Sets the value of the ecProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcProfile(String value) {
        this.ecProfile = value;
    }

    /**
     * Gets the value of the atProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtProfile() {
        return atProfile;
    }

    /**
     * Sets the value of the atProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtProfile(String value) {
        this.atProfile = value;
    }

    /**
     * Gets the value of the itsValidFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItsValidFrom() {
        return itsValidFrom;
    }

    /**
     * Sets the value of the itsValidFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItsValidFrom(XMLGregorianCalendar value) {
        this.itsValidFrom = value;
    }

    /**
     * Gets the value of the itsValidTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItsValidTo() {
        return itsValidTo;
    }

    /**
     * Sets the value of the itsValidTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItsValidTo(XMLGregorianCalendar value) {
        this.itsValidTo = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsType }
     *     
     */
    public RegionsType getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsType }
     *     
     */
    public void setRegions(RegionsType value) {
        this.regions = value;
    }

}
