//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.01 at 07:07:29 AM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.certificateservices.messages.csmessages.jaxb.CSResponse;


/**
 * <p>Java class for BaseV2XResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseV2XResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/csmessages2_0}CSResponse">
 *       &lt;sequence>
 *         &lt;element name="itsId" type="{http://certificateservices.org/xsd/v2x_2_0}ItsIdType"/>
 *         &lt;element name="user" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *         &lt;element name="userDisplayName" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *         &lt;element name="ecuType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *         &lt;element name="ecInitPublicKey" type="{http://certificateservices.org/xsd/v2x_2_0}InitECKeyType"/>
 *         &lt;element name="ecProfile" type="{http://certificateservices.org/xsd/v2x_2_0}ProfileNameType" minOccurs="0"/>
 *         &lt;element name="atProfile" type="{http://certificateservices.org/xsd/v2x_2_0}ProfileNameType" minOccurs="0"/>
 *         &lt;element name="itsValidFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="itsValidTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="regions" type="{http://certificateservices.org/xsd/v2x_2_0}RegionsType" minOccurs="0"/>
 *         &lt;element name="itsStatus" type="{http://certificateservices.org/xsd/v2x_2_0}ITSStatusType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseV2XResponseType", propOrder = {
    "itsId",
    "user",
    "userDisplayName",
    "ecuType",
    "ecInitPublicKey",
    "ecProfile",
    "atProfile",
    "itsValidFrom",
    "itsValidTo",
    "regions",
    "itsStatus"
})
@XmlSeeAlso({
    GetITSDataResponse.class,
    UpdateITSResponse.class,
    RegisterITSResponse.class,
    DeactivateITSResponse.class
})
public class BaseV2XResponseType
    extends CSResponse
{

    @XmlElement(required = true)
    protected byte[] itsId;
    @XmlElement(required = true)
    protected String user;
    @XmlElement(required = true)
    protected String userDisplayName;
    @XmlElement(required = true)
    protected String ecuType;
    @XmlElement(required = true)
    protected InitECKeyType ecInitPublicKey;
    protected String ecProfile;
    protected String atProfile;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itsValidFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar itsValidTo;
    protected RegionsType regions;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ITSStatusType itsStatus;

    /**
     * Gets the value of the itsId property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getItsId() {
        return itsId;
    }

    /**
     * Sets the value of the itsId property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setItsId(byte[] value) {
        this.itsId = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the userDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDisplayName() {
        return userDisplayName;
    }

    /**
     * Sets the value of the userDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDisplayName(String value) {
        this.userDisplayName = value;
    }

    /**
     * Gets the value of the ecuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcuType() {
        return ecuType;
    }

    /**
     * Sets the value of the ecuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcuType(String value) {
        this.ecuType = value;
    }

    /**
     * Gets the value of the ecInitPublicKey property.
     * 
     * @return
     *     possible object is
     *     {@link InitECKeyType }
     *     
     */
    public InitECKeyType getEcInitPublicKey() {
        return ecInitPublicKey;
    }

    /**
     * Sets the value of the ecInitPublicKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitECKeyType }
     *     
     */
    public void setEcInitPublicKey(InitECKeyType value) {
        this.ecInitPublicKey = value;
    }

    /**
     * Gets the value of the ecProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcProfile() {
        return ecProfile;
    }

    /**
     * Sets the value of the ecProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcProfile(String value) {
        this.ecProfile = value;
    }

    /**
     * Gets the value of the atProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtProfile() {
        return atProfile;
    }

    /**
     * Sets the value of the atProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtProfile(String value) {
        this.atProfile = value;
    }

    /**
     * Gets the value of the itsValidFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItsValidFrom() {
        return itsValidFrom;
    }

    /**
     * Sets the value of the itsValidFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItsValidFrom(XMLGregorianCalendar value) {
        this.itsValidFrom = value;
    }

    /**
     * Gets the value of the itsValidTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getItsValidTo() {
        return itsValidTo;
    }

    /**
     * Sets the value of the itsValidTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setItsValidTo(XMLGregorianCalendar value) {
        this.itsValidTo = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsType }
     *     
     */
    public RegionsType getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsType }
     *     
     */
    public void setRegions(RegionsType value) {
        this.regions = value;
    }

    /**
     * Gets the value of the itsStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ITSStatusType }
     *     
     */
    public ITSStatusType getItsStatus() {
        return itsStatus;
    }

    /**
     * Sets the value of the itsStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITSStatusType }
     *     
     */
    public void setItsStatus(ITSStatusType value) {
        this.itsStatus = value;
    }

}
