//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.01 at 07:07:29 AM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InitECKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitECKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="publicKeyInfos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="publicVerificationKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                   &lt;element name="publicEncryptionKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitECKeyType", propOrder = {
    "publicKeyInfos"
})
public class InitECKeyType {

    protected InitECKeyType.PublicKeyInfos publicKeyInfos;

    /**
     * Gets the value of the publicKeyInfos property.
     * 
     * @return
     *     possible object is
     *     {@link InitECKeyType.PublicKeyInfos }
     *     
     */
    public InitECKeyType.PublicKeyInfos getPublicKeyInfos() {
        return publicKeyInfos;
    }

    /**
     * Sets the value of the publicKeyInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitECKeyType.PublicKeyInfos }
     *     
     */
    public void setPublicKeyInfos(InitECKeyType.PublicKeyInfos value) {
        this.publicKeyInfos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="publicVerificationKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *         &lt;element name="publicEncryptionKey" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "publicVerificationKey",
        "publicEncryptionKey"
    })
    public static class PublicKeyInfos {

        @XmlElement(required = true)
        protected byte[] publicVerificationKey;
        protected byte[] publicEncryptionKey;

        /**
         * Gets the value of the publicVerificationKey property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getPublicVerificationKey() {
            return publicVerificationKey;
        }

        /**
         * Sets the value of the publicVerificationKey property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setPublicVerificationKey(byte[] value) {
            this.publicVerificationKey = value;
        }

        /**
         * Gets the value of the publicEncryptionKey property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getPublicEncryptionKey() {
            return publicEncryptionKey;
        }

        /**
         * Sets the value of the publicEncryptionKey property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setPublicEncryptionKey(byte[] value) {
            this.publicEncryptionKey = value;
        }

    }

}
