//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.01 at 07:07:29 AM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ITSStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ITSStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="REGISTERED"/>
 *     &lt;enumeration value="ENROLLED"/>
 *     &lt;enumeration value="INACTIVE"/>
 *     &lt;enumeration value="NOTYETVALID"/>
 *     &lt;enumeration value="EXPIRED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ITSStatusType")
@XmlEnum
public enum ITSStatusType {

    REGISTERED,
    ENROLLED,
    INACTIVE,
    NOTYETVALID,
    EXPIRED;

    public String value() {
        return name();
    }

    public static ITSStatusType fromValue(String v) {
        return valueOf(v);
    }

}
