//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.05 at 01:26:51 PM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.v2x.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.v2x.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegionsType }
     * 
     */
    public RegionsType createRegionsType() {
        return new RegionsType();
    }

    /**
     * Create an instance of {@link RegisterITSRequest }
     * 
     */
    public RegisterITSRequest createRegisterITSRequest() {
        return new RegisterITSRequest();
    }

    /**
     * Create an instance of {@link BaseRegisterRequestType }
     * 
     */
    public BaseRegisterRequestType createBaseRegisterRequestType() {
        return new BaseRegisterRequestType();
    }

    /**
     * Create an instance of {@link InitECKeyType }
     * 
     */
    public InitECKeyType createInitECKeyType() {
        return new InitECKeyType();
    }

    /**
     * Create an instance of {@link ATAppPermissionsType }
     * 
     */
    public ATAppPermissionsType createATAppPermissionsType() {
        return new ATAppPermissionsType();
    }

    /**
     * Create an instance of {@link ReactivateITSResponse }
     * 
     */
    public ReactivateITSResponse createReactivateITSResponse() {
        return new ReactivateITSResponse();
    }

    /**
     * Create an instance of {@link BaseV2XResponseType }
     * 
     */
    public BaseV2XResponseType createBaseV2XResponseType() {
        return new BaseV2XResponseType();
    }

    /**
     * Create an instance of {@link DeactivateITSResponse }
     * 
     */
    public DeactivateITSResponse createDeactivateITSResponse() {
        return new DeactivateITSResponse();
    }

    /**
     * Create an instance of {@link DeactivateITSRequest }
     * 
     */
    public DeactivateITSRequest createDeactivateITSRequest() {
        return new DeactivateITSRequest();
    }

    /**
     * Create an instance of {@link RegisterITSResponse }
     * 
     */
    public RegisterITSResponse createRegisterITSResponse() {
        return new RegisterITSResponse();
    }

    /**
     * Create an instance of {@link GetITSDataRequest }
     * 
     */
    public GetITSDataRequest createGetITSDataRequest() {
        return new GetITSDataRequest();
    }

    /**
     * Create an instance of {@link ReactivateITSRequest }
     * 
     */
    public ReactivateITSRequest createReactivateITSRequest() {
        return new ReactivateITSRequest();
    }

    /**
     * Create an instance of {@link UpdateITSRequest }
     * 
     */
    public UpdateITSRequest createUpdateITSRequest() {
        return new UpdateITSRequest();
    }

    /**
     * Create an instance of {@link UpdateITSResponse }
     * 
     */
    public UpdateITSResponse createUpdateITSResponse() {
        return new UpdateITSResponse();
    }

    /**
     * Create an instance of {@link GetITSDataResponse }
     * 
     */
    public GetITSDataResponse createGetITSDataResponse() {
        return new GetITSDataResponse();
    }

    /**
     * Create an instance of {@link AppPermissionsType }
     * 
     */
    public AppPermissionsType createAppPermissionsType() {
        return new AppPermissionsType();
    }

    /**
     * Create an instance of {@link RegionsType.IdentifiedRegions }
     * 
     */
    public RegionsType.IdentifiedRegions createRegionsTypeIdentifiedRegions() {
        return new RegionsType.IdentifiedRegions();
    }

}
