//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.05 at 01:26:51 PM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/v2x_2_0}BaseRegisterRequestType">
 *       &lt;sequence>
 *         &lt;element name="ecuType" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring"/>
 *         &lt;element name="ecInitPublicKey" type="{http://certificateservices.org/xsd/v2x_2_0}InitECKeyType"/>
 *         &lt;element name="atPermissions" type="{http://certificateservices.org/xsd/v2x_2_0}ATAppPermissionsType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ecuType",
    "ecInitPublicKey",
    "atPermissions"
})
@XmlRootElement(name = "RegisterITSRequest")
public class RegisterITSRequest
    extends BaseRegisterRequestType
{

    @XmlElement(required = true)
    protected String ecuType;
    @XmlElement(required = true)
    protected InitECKeyType ecInitPublicKey;
    @XmlElement(required = true)
    protected ATAppPermissionsType atPermissions;

    /**
     * Gets the value of the ecuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcuType() {
        return ecuType;
    }

    /**
     * Sets the value of the ecuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcuType(String value) {
        this.ecuType = value;
    }

    /**
     * Gets the value of the ecInitPublicKey property.
     * 
     * @return
     *     possible object is
     *     {@link InitECKeyType }
     *     
     */
    public InitECKeyType getEcInitPublicKey() {
        return ecInitPublicKey;
    }

    /**
     * Sets the value of the ecInitPublicKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitECKeyType }
     *     
     */
    public void setEcInitPublicKey(InitECKeyType value) {
        this.ecInitPublicKey = value;
    }

    /**
     * Gets the value of the atPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link ATAppPermissionsType }
     *     
     */
    public ATAppPermissionsType getAtPermissions() {
        return atPermissions;
    }

    /**
     * Sets the value of the atPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATAppPermissionsType }
     *     
     */
    public void setAtPermissions(ATAppPermissionsType value) {
        this.atPermissions = value;
    }

}
