//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.01 at 07:07:29 AM CET 
//


package org.certificateservices.messages.v2x.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://certificateservices.org/xsd/v2x_2_0}BaseRegisterRequestType">
 *       &lt;sequence>
 *         &lt;element name="user" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
 *         &lt;element name="userDisplayName" type="{http://certificateservices.org/xsd/csmessages2_0}notemptystring" minOccurs="0"/>
 *         &lt;element name="ecInitPublicKey" type="{http://certificateservices.org/xsd/v2x_2_0}InitECKeyType" minOccurs="0"/>
 *         &lt;element name="itsStatus" type="{http://certificateservices.org/xsd/v2x_2_0}ITSStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "user",
    "userDisplayName",
    "ecInitPublicKey",
    "itsStatus"
})
@XmlRootElement(name = "UpdateITSRequest")
public class UpdateITSRequest
    extends BaseRegisterRequestType
{

    protected String user;
    protected String userDisplayName;
    protected InitECKeyType ecInitPublicKey;
    @XmlSchemaType(name = "string")
    protected ITSStatusType itsStatus;

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the userDisplayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDisplayName() {
        return userDisplayName;
    }

    /**
     * Sets the value of the userDisplayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDisplayName(String value) {
        this.userDisplayName = value;
    }

    /**
     * Gets the value of the ecInitPublicKey property.
     * 
     * @return
     *     possible object is
     *     {@link InitECKeyType }
     *     
     */
    public InitECKeyType getEcInitPublicKey() {
        return ecInitPublicKey;
    }

    /**
     * Sets the value of the ecInitPublicKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitECKeyType }
     *     
     */
    public void setEcInitPublicKey(InitECKeyType value) {
        this.ecInitPublicKey = value;
    }

    /**
     * Gets the value of the itsStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ITSStatusType }
     *     
     */
    public ITSStatusType getItsStatus() {
        return itsStatus;
    }

    /**
     * Sets the value of the itsStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ITSStatusType }
     *     
     */
    public void setItsStatus(ITSStatusType value) {
        this.itsStatus = value;
    }

}
