//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 09:01:03 AM CET 
//


package org.certificateservices.messages.authorization.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.authorization.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.authorization.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRolesType }
     * 
     */
    public GetRolesType createGetRolesType() {
        return new GetRolesType();
    }

    /**
     * Create an instance of {@link GetRequesterRolesRequest }
     * 
     */
    public GetRequesterRolesRequest createGetRequesterRolesRequest() {
        return new GetRequesterRolesRequest();
    }

    /**
     * Create an instance of {@link GetRequesterRolesResponse }
     * 
     */
    public GetRequesterRolesResponse createGetRequesterRolesResponse() {
        return new GetRequesterRolesResponse();
    }

    /**
     * Create an instance of {@link GetRolesType.Roles }
     * 
     */
    public GetRolesType.Roles createGetRolesTypeRoles() {
        return new GetRolesType.Roles();
    }

}
