//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.27 at 11:55:56 AM CEST 
//


package org.certificateservices.messages.credmanagement.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.credmanagement.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.credmanagement.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUsersResponse }
     * 
     */
    public GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link GetTokensResponse }
     * 
     */
    public GetTokensResponse createGetTokensResponse() {
        return new GetTokensResponse();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsRequest }
     * 
     */
    public IssueTokenCredentialsRequest createIssueTokenCredentialsRequest() {
        return new IssueTokenCredentialsRequest();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsResponse }
     * 
     */
    public IssueTokenCredentialsResponse createIssueTokenCredentialsResponse() {
        return new IssueTokenCredentialsResponse();
    }

    /**
     * Create an instance of {@link GetUsersResponse.Users }
     * 
     */
    public GetUsersResponse.Users createGetUsersResponseUsers() {
        return new GetUsersResponse.Users();
    }

    /**
     * Create an instance of {@link GetCredentialResponse }
     * 
     */
    public GetCredentialResponse createGetCredentialResponse() {
        return new GetCredentialResponse();
    }

    /**
     * Create an instance of {@link IssueCredentialStatusListRequest }
     * 
     */
    public IssueCredentialStatusListRequest createIssueCredentialStatusListRequest() {
        return new IssueCredentialStatusListRequest();
    }

    /**
     * Create an instance of {@link RemoveCredentialResponse }
     * 
     */
    public RemoveCredentialResponse createRemoveCredentialResponse() {
        return new RemoveCredentialResponse();
    }

    /**
     * Create an instance of {@link FetchHardTokenDataRequest }
     * 
     */
    public FetchHardTokenDataRequest createFetchHardTokenDataRequest() {
        return new FetchHardTokenDataRequest();
    }

    /**
     * Create an instance of {@link ChangeCredentialStatusResponse }
     * 
     */
    public ChangeCredentialStatusResponse createChangeCredentialStatusResponse() {
        return new ChangeCredentialStatusResponse();
    }

    /**
     * Create an instance of {@link StoreHardTokenDataRequest }
     * 
     */
    public StoreHardTokenDataRequest createStoreHardTokenDataRequest() {
        return new StoreHardTokenDataRequest();
    }

    /**
     * Create an instance of {@link GetCredentialRequest }
     * 
     */
    public GetCredentialRequest createGetCredentialRequest() {
        return new GetCredentialRequest();
    }

    /**
     * Create an instance of {@link GetUsersRequest }
     * 
     */
    public GetUsersRequest createGetUsersRequest() {
        return new GetUsersRequest();
    }

    /**
     * Create an instance of {@link ChangeCredentialStatusRequest }
     * 
     */
    public ChangeCredentialStatusRequest createChangeCredentialStatusRequest() {
        return new ChangeCredentialStatusRequest();
    }

    /**
     * Create an instance of {@link GetTokensRequest }
     * 
     */
    public GetTokensRequest createGetTokensRequest() {
        return new GetTokensRequest();
    }

    /**
     * Create an instance of {@link GetCredentialStatusListResponse }
     * 
     */
    public GetCredentialStatusListResponse createGetCredentialStatusListResponse() {
        return new GetCredentialStatusListResponse();
    }

    /**
     * Create an instance of {@link GetTokensResponse.Tokens }
     * 
     */
    public GetTokensResponse.Tokens createGetTokensResponseTokens() {
        return new GetTokensResponse.Tokens();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsRequest.FieldValues }
     * 
     */
    public IssueTokenCredentialsRequest.FieldValues createIssueTokenCredentialsRequestFieldValues() {
        return new IssueTokenCredentialsRequest.FieldValues();
    }

    /**
     * Create an instance of {@link HardTokenData }
     * 
     */
    public HardTokenData createHardTokenData() {
        return new HardTokenData();
    }

    /**
     * Create an instance of {@link RemoveCredentialRequest }
     * 
     */
    public RemoveCredentialRequest createRemoveCredentialRequest() {
        return new RemoveCredentialRequest();
    }

    /**
     * Create an instance of {@link StoreHardTokenDataResponse }
     * 
     */
    public StoreHardTokenDataResponse createStoreHardTokenDataResponse() {
        return new StoreHardTokenDataResponse();
    }

    /**
     * Create an instance of {@link GetCredentialStatusListRequest }
     * 
     */
    public GetCredentialStatusListRequest createGetCredentialStatusListRequest() {
        return new GetCredentialStatusListRequest();
    }

    /**
     * Create an instance of {@link GetIssuerCredentialsRequest }
     * 
     */
    public GetIssuerCredentialsRequest createGetIssuerCredentialsRequest() {
        return new GetIssuerCredentialsRequest();
    }

    /**
     * Create an instance of {@link IsIssuerRequest }
     * 
     */
    public IsIssuerRequest createIsIssuerRequest() {
        return new IsIssuerRequest();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsResponse.Credentials }
     * 
     */
    public IssueTokenCredentialsResponse.Credentials createIssueTokenCredentialsResponseCredentials() {
        return new IssueTokenCredentialsResponse.Credentials();
    }

    /**
     * Create an instance of {@link IssueTokenCredentialsResponse.RevokedCredentials }
     * 
     */
    public IssueTokenCredentialsResponse.RevokedCredentials createIssueTokenCredentialsResponseRevokedCredentials() {
        return new IssueTokenCredentialsResponse.RevokedCredentials();
    }

    /**
     * Create an instance of {@link FetchHardTokenDataResponse }
     * 
     */
    public FetchHardTokenDataResponse createFetchHardTokenDataResponse() {
        return new FetchHardTokenDataResponse();
    }

    /**
     * Create an instance of {@link IsIssuerResponse }
     * 
     */
    public IsIssuerResponse createIsIssuerResponse() {
        return new IsIssuerResponse();
    }

    /**
     * Create an instance of {@link GetIssuerCredentialsResponse }
     * 
     */
    public GetIssuerCredentialsResponse createGetIssuerCredentialsResponse() {
        return new GetIssuerCredentialsResponse();
    }

    /**
     * Create an instance of {@link IssueCredentialStatusListResponse }
     * 
     */
    public IssueCredentialStatusListResponse createIssueCredentialStatusListResponse() {
        return new IssueCredentialStatusListResponse();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

}
