//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.13 at 03:22:10 PM CEST 
//


package org.certificateservices.messages.csexport.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainNameRestriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomainNameRestriction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domainNameValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allowSubDomains" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowWildCard" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainNameRestriction", propOrder = {
    "domainNameValue",
    "allowSubDomains",
    "allowWildCard"
})
public class DomainNameRestriction {

    @XmlElement(required = true)
    protected String domainNameValue;
    protected boolean allowSubDomains;
    protected boolean allowWildCard;

    /**
     * Gets the value of the domainNameValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainNameValue() {
        return domainNameValue;
    }

    /**
     * Sets the value of the domainNameValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainNameValue(String value) {
        this.domainNameValue = value;
    }

    /**
     * Gets the value of the allowSubDomains property.
     * 
     */
    public boolean isAllowSubDomains() {
        return allowSubDomains;
    }

    /**
     * Sets the value of the allowSubDomains property.
     * 
     */
    public void setAllowSubDomains(boolean value) {
        this.allowSubDomains = value;
    }

    /**
     * Gets the value of the allowWildCard property.
     * 
     */
    public boolean isAllowWildCard() {
        return allowWildCard;
    }

    /**
     * Sets the value of the allowWildCard property.
     * 
     */
    public void setAllowWildCard(boolean value) {
        this.allowWildCard = value;
    }

}
