//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.09 at 01:10:41 PM MSK 
//


package org.certificateservices.messages.sweeid2.dssextenstions1_1.jaxp;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.certificateservices.messages.saml2.assertion.jaxb.AttributeStatementType;
import org.certificateservices.messages.saml2.assertion.jaxb.ConditionsType;
import org.certificateservices.messages.saml2.assertion.jaxb.EncryptedElementType;
import org.certificateservices.messages.saml2.assertion.jaxb.NameIDType;
import org.certificateservices.messages.xmldsig.jaxb.KeyInfoType;
import org.certificateservices.messages.xmldsig.jaxb.TransformType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.certificateservices.messages.sweeid2.dssextenstions1_1.jaxp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SignRequestExtension_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignRequestExtension");
    private final static QName _AdESObject_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "AdESObject");
    private final static QName _SignatureCertificateChain_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignatureCertificateChain");
    private final static QName _EncryptionProperties_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "EncryptionProperties");
    private final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    private final static QName _EncryptedKey_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "EncryptedKey");
    private final static QName _OtherRequestInfo_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "OtherRequestInfo");
    private final static QName _Message_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "Message");
    private final static QName _OtherSignTaskData_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "OtherSignTaskData");
    private final static QName _SignMessage_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignMessage");
    private final static QName _EncryptedMessage_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "EncryptedMessage");
    private final static QName _ResponseTime_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "ResponseTime");
    private final static QName _RequestedCertAttributes_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "RequestedCertAttributes");
    private final static QName _SignTasks_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignTasks");
    private final static QName _ContextInfo_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "ContextInfo");
    private final static QName _EncryptedData_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "EncryptedData");
    private final static QName _Conditions_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:assertion", "Conditions");
    private final static QName _Signer_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "Signer");
    private final static QName _OtherResponseInfo_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "OtherResponseInfo");
    private final static QName _SignService_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignService");
    private final static QName _RequestedSignatureAlgorithm_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "RequestedSignatureAlgorithm");
    private final static QName _EncryptionProperty_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "EncryptionProperty");
    private final static QName _AttributeStatement_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AttributeStatement");
    private final static QName _Request_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "Request");
    private final static QName _RequestTime_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "RequestTime");
    private final static QName _IdentityProvider_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "IdentityProvider");
    private final static QName _SignResponseExtension_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignResponseExtension");
    private final static QName _Base64Signature_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "Base64Signature");
    private final static QName _SignRequester_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignRequester");
    private final static QName _SignerAssertionInfo_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignerAssertionInfo");
    private final static QName _CipherData_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "CipherData");
    private final static QName _Transform_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transform");
    private final static QName _CertRequestProperties_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "CertRequestProperties");
    private final static QName _CipherReference_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "CipherReference");
    private final static QName _ToBeSignedBytes_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "ToBeSignedBytes");
    private final static QName _OtherProperties_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "OtherProperties");
    private final static QName _AgreementMethod_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "AgreementMethod");
    private final static QName _SamlAssertions_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SamlAssertions");
    private final static QName _AuthnContextClassRef_QNAME = new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextClassRef");
    private final static QName _SignTaskData_QNAME = new QName("http://id.elegnamnden.se/csig/1.1/dss-ext/ns", "SignTaskData");
    private final static QName _EncryptionMethodTypeKeySize_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "KeySize");
    private final static QName _EncryptionMethodTypeOAEPparams_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "OAEPparams");
    private final static QName _ReferenceListDataReference_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "DataReference");
    private final static QName _ReferenceListKeyReference_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "KeyReference");
    private final static QName _AgreementMethodTypeKANonce_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "KA-Nonce");
    private final static QName _AgreementMethodTypeOriginatorKeyInfo_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "OriginatorKeyInfo");
    private final static QName _AgreementMethodTypeRecipientKeyInfo_QNAME = new QName("http://www.w3.org/2001/04/xmlenc#", "RecipientKeyInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.certificateservices.messages.sweeid2.dssextenstions1_1.jaxp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnyType }
     * 
     */
    public AnyType createAnyType() {
        return new AnyType();
    }

    /**
     * Create an instance of {@link SignRequestExtensionType }
     * 
     */
    public SignRequestExtensionType createSignRequestExtensionType() {
        return new SignRequestExtensionType();
    }

    /**
     * Create an instance of {@link AdESObjectType }
     * 
     */
    public AdESObjectType createAdESObjectType() {
        return new AdESObjectType();
    }

    /**
     * Create an instance of {@link CertificateChainType }
     * 
     */
    public CertificateChainType createCertificateChainType() {
        return new CertificateChainType();
    }

    /**
     * Create an instance of {@link SignMessageType }
     * 
     */
    public SignMessageType createSignMessageType() {
        return new SignMessageType();
    }

    /**
     * Create an instance of {@link SignTasksType }
     * 
     */
    public SignTasksType createSignTasksType() {
        return new SignTasksType();
    }

    /**
     * Create an instance of {@link ContextInfoType }
     * 
     */
    public ContextInfoType createContextInfoType() {
        return new ContextInfoType();
    }

    /**
     * Create an instance of {@link RequestedAttributesType }
     * 
     */
    public RequestedAttributesType createRequestedAttributesType() {
        return new RequestedAttributesType();
    }

    /**
     * Create an instance of {@link SignerAssertionInfoType }
     * 
     */
    public SignerAssertionInfoType createSignerAssertionInfoType() {
        return new SignerAssertionInfoType();
    }

    /**
     * Create an instance of {@link SignResponseExtensionType }
     * 
     */
    public SignResponseExtensionType createSignResponseExtensionType() {
        return new SignResponseExtensionType();
    }

    /**
     * Create an instance of {@link Base64SignatureType }
     * 
     */
    public Base64SignatureType createBase64SignatureType() {
        return new Base64SignatureType();
    }

    /**
     * Create an instance of {@link SignTaskDataType }
     * 
     */
    public SignTaskDataType createSignTaskDataType() {
        return new SignTaskDataType();
    }

    /**
     * Create an instance of {@link SAMLAssertionsType }
     * 
     */
    public SAMLAssertionsType createSAMLAssertionsType() {
        return new SAMLAssertionsType();
    }

    /**
     * Create an instance of {@link CertRequestPropertiesType }
     * 
     */
    public CertRequestPropertiesType createCertRequestPropertiesType() {
        return new CertRequestPropertiesType();
    }

    /**
     * Create an instance of {@link PreferredSAMLAttributeNameType }
     * 
     */
    public PreferredSAMLAttributeNameType createPreferredSAMLAttributeNameType() {
        return new PreferredSAMLAttributeNameType();
    }

    /**
     * Create an instance of {@link MappedAttributeType }
     * 
     */
    public MappedAttributeType createMappedAttributeType() {
        return new MappedAttributeType();
    }

    /**
     * Create an instance of {@link EncryptionPropertyType }
     * 
     */
    public EncryptionPropertyType createEncryptionPropertyType() {
        return new EncryptionPropertyType();
    }

    /**
     * Create an instance of {@link CipherDataType }
     * 
     */
    public CipherDataType createCipherDataType() {
        return new CipherDataType();
    }

    /**
     * Create an instance of {@link AgreementMethodType }
     * 
     */
    public AgreementMethodType createAgreementMethodType() {
        return new AgreementMethodType();
    }

    /**
     * Create an instance of {@link EncryptedKeyType }
     * 
     */
    public EncryptedKeyType createEncryptedKeyType() {
        return new EncryptedKeyType();
    }

    /**
     * Create an instance of {@link EncryptionPropertiesType }
     * 
     */
    public EncryptionPropertiesType createEncryptionPropertiesType() {
        return new EncryptionPropertiesType();
    }

    /**
     * Create an instance of {@link EncryptedDataType }
     * 
     */
    public EncryptedDataType createEncryptedDataType() {
        return new EncryptedDataType();
    }

    /**
     * Create an instance of {@link CipherReferenceType }
     * 
     */
    public CipherReferenceType createCipherReferenceType() {
        return new CipherReferenceType();
    }

    /**
     * Create an instance of {@link ReferenceList }
     * 
     */
    public ReferenceList createReferenceList() {
        return new ReferenceList();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link EncryptionMethodType }
     * 
     */
    public EncryptionMethodType createEncryptionMethodType() {
        return new EncryptionMethodType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignRequestExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignRequestExtension")
    public JAXBElement<SignRequestExtensionType> createSignRequestExtension(SignRequestExtensionType value) {
        return new JAXBElement<SignRequestExtensionType>(_SignRequestExtension_QNAME, SignRequestExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdESObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "AdESObject")
    public JAXBElement<AdESObjectType> createAdESObject(AdESObjectType value) {
        return new JAXBElement<AdESObjectType>(_AdESObject_QNAME, AdESObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertificateChainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignatureCertificateChain")
    public JAXBElement<CertificateChainType> createSignatureCertificateChain(CertificateChainType value) {
        return new JAXBElement<CertificateChainType>(_SignatureCertificateChain_QNAME, CertificateChainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptionPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "EncryptionProperties")
    public JAXBElement<EncryptionPropertiesType> createEncryptionProperties(EncryptionPropertiesType value) {
        return new JAXBElement<EncryptionPropertiesType>(_EncryptionProperties_QNAME, EncryptionPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyInfo")
    public JAXBElement<KeyInfoType> createKeyInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_KeyInfo_QNAME, KeyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptedKeyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "EncryptedKey")
    public JAXBElement<EncryptedKeyType> createEncryptedKey(EncryptedKeyType value) {
        return new JAXBElement<EncryptedKeyType>(_EncryptedKey_QNAME, EncryptedKeyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "OtherRequestInfo")
    public JAXBElement<AnyType> createOtherRequestInfo(AnyType value) {
        return new JAXBElement<AnyType>(_OtherRequestInfo_QNAME, AnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "Message")
    public JAXBElement<byte[]> createMessage(byte[] value) {
        return new JAXBElement<byte[]>(_Message_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "OtherSignTaskData")
    public JAXBElement<AnyType> createOtherSignTaskData(AnyType value) {
        return new JAXBElement<AnyType>(_OtherSignTaskData_QNAME, AnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignMessage")
    public JAXBElement<SignMessageType> createSignMessage(SignMessageType value) {
        return new JAXBElement<SignMessageType>(_SignMessage_QNAME, SignMessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptedElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "EncryptedMessage")
    public JAXBElement<EncryptedElementType> createEncryptedMessage(EncryptedElementType value) {
        return new JAXBElement<EncryptedElementType>(_EncryptedMessage_QNAME, EncryptedElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "ResponseTime")
    public JAXBElement<XMLGregorianCalendar> createResponseTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ResponseTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestedAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "RequestedCertAttributes")
    public JAXBElement<RequestedAttributesType> createRequestedCertAttributes(RequestedAttributesType value) {
        return new JAXBElement<RequestedAttributesType>(_RequestedCertAttributes_QNAME, RequestedAttributesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignTasksType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignTasks")
    public JAXBElement<SignTasksType> createSignTasks(SignTasksType value) {
        return new JAXBElement<SignTasksType>(_SignTasks_QNAME, SignTasksType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContextInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "ContextInfo")
    public JAXBElement<ContextInfoType> createContextInfo(ContextInfoType value) {
        return new JAXBElement<ContextInfoType>(_ContextInfo_QNAME, ContextInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptedDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "EncryptedData")
    public JAXBElement<EncryptedDataType> createEncryptedData(EncryptedDataType value) {
        return new JAXBElement<EncryptedDataType>(_EncryptedData_QNAME, EncryptedDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:assertion", name = "Conditions")
    public JAXBElement<ConditionsType> createConditions(ConditionsType value) {
        return new JAXBElement<ConditionsType>(_Conditions_QNAME, ConditionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeStatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "Signer")
    public JAXBElement<AttributeStatementType> createSigner(AttributeStatementType value) {
        return new JAXBElement<AttributeStatementType>(_Signer_QNAME, AttributeStatementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "OtherResponseInfo")
    public JAXBElement<AnyType> createOtherResponseInfo(AnyType value) {
        return new JAXBElement<AnyType>(_OtherResponseInfo_QNAME, AnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignService")
    public JAXBElement<NameIDType> createSignService(NameIDType value) {
        return new JAXBElement<NameIDType>(_SignService_QNAME, NameIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "RequestedSignatureAlgorithm")
    public JAXBElement<String> createRequestedSignatureAlgorithm(String value) {
        return new JAXBElement<String>(_RequestedSignatureAlgorithm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptionPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "EncryptionProperty")
    public JAXBElement<EncryptionPropertyType> createEncryptionProperty(EncryptionPropertyType value) {
        return new JAXBElement<EncryptionPropertyType>(_EncryptionProperty_QNAME, EncryptionPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeStatementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:assertion", name = "AttributeStatement")
    public JAXBElement<AttributeStatementType> createAttributeStatement(AttributeStatementType value) {
        return new JAXBElement<AttributeStatementType>(_AttributeStatement_QNAME, AttributeStatementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "Request")
    public JAXBElement<byte[]> createRequest(byte[] value) {
        return new JAXBElement<byte[]>(_Request_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "RequestTime")
    public JAXBElement<XMLGregorianCalendar> createRequestTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "IdentityProvider")
    public JAXBElement<NameIDType> createIdentityProvider(NameIDType value) {
        return new JAXBElement<NameIDType>(_IdentityProvider_QNAME, NameIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignResponseExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignResponseExtension")
    public JAXBElement<SignResponseExtensionType> createSignResponseExtension(SignResponseExtensionType value) {
        return new JAXBElement<SignResponseExtensionType>(_SignResponseExtension_QNAME, SignResponseExtensionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Base64SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "Base64Signature")
    public JAXBElement<Base64SignatureType> createBase64Signature(Base64SignatureType value) {
        return new JAXBElement<Base64SignatureType>(_Base64Signature_QNAME, Base64SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignRequester")
    public JAXBElement<NameIDType> createSignRequester(NameIDType value) {
        return new JAXBElement<NameIDType>(_SignRequester_QNAME, NameIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignerAssertionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignerAssertionInfo")
    public JAXBElement<SignerAssertionInfoType> createSignerAssertionInfo(SignerAssertionInfoType value) {
        return new JAXBElement<SignerAssertionInfoType>(_SignerAssertionInfo_QNAME, SignerAssertionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CipherDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "CipherData")
    public JAXBElement<CipherDataType> createCipherData(CipherDataType value) {
        return new JAXBElement<CipherDataType>(_CipherData_QNAME, CipherDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transform")
    public JAXBElement<TransformType> createTransform(TransformType value) {
        return new JAXBElement<TransformType>(_Transform_QNAME, TransformType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CertRequestPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "CertRequestProperties")
    public JAXBElement<CertRequestPropertiesType> createCertRequestProperties(CertRequestPropertiesType value) {
        return new JAXBElement<CertRequestPropertiesType>(_CertRequestProperties_QNAME, CertRequestPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CipherReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "CipherReference")
    public JAXBElement<CipherReferenceType> createCipherReference(CipherReferenceType value) {
        return new JAXBElement<CipherReferenceType>(_CipherReference_QNAME, CipherReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "ToBeSignedBytes")
    public JAXBElement<byte[]> createToBeSignedBytes(byte[] value) {
        return new JAXBElement<byte[]>(_ToBeSignedBytes_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "OtherProperties")
    public JAXBElement<AnyType> createOtherProperties(AnyType value) {
        return new JAXBElement<AnyType>(_OtherProperties_QNAME, AnyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgreementMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "AgreementMethod")
    public JAXBElement<AgreementMethodType> createAgreementMethod(AgreementMethodType value) {
        return new JAXBElement<AgreementMethodType>(_AgreementMethod_QNAME, AgreementMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAMLAssertionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SamlAssertions")
    public JAXBElement<SAMLAssertionsType> createSamlAssertions(SAMLAssertionsType value) {
        return new JAXBElement<SAMLAssertionsType>(_SamlAssertions_QNAME, SAMLAssertionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oasis:names:tc:SAML:2.0:assertion", name = "AuthnContextClassRef")
    public JAXBElement<String> createAuthnContextClassRef(String value) {
        return new JAXBElement<String>(_AuthnContextClassRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignTaskDataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://id.elegnamnden.se/csig/1.1/dss-ext/ns", name = "SignTaskData")
    public JAXBElement<SignTaskDataType> createSignTaskData(SignTaskDataType value) {
        return new JAXBElement<SignTaskDataType>(_SignTaskData_QNAME, SignTaskDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "KeySize", scope = EncryptionMethodType.class)
    public JAXBElement<BigInteger> createEncryptionMethodTypeKeySize(BigInteger value) {
        return new JAXBElement<BigInteger>(_EncryptionMethodTypeKeySize_QNAME, BigInteger.class, EncryptionMethodType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "OAEPparams", scope = EncryptionMethodType.class)
    public JAXBElement<byte[]> createEncryptionMethodTypeOAEPparams(byte[] value) {
        return new JAXBElement<byte[]>(_EncryptionMethodTypeOAEPparams_QNAME, byte[].class, EncryptionMethodType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "DataReference", scope = ReferenceList.class)
    public JAXBElement<ReferenceType> createReferenceListDataReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_ReferenceListDataReference_QNAME, ReferenceType.class, ReferenceList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "KeyReference", scope = ReferenceList.class)
    public JAXBElement<ReferenceType> createReferenceListKeyReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_ReferenceListKeyReference_QNAME, ReferenceType.class, ReferenceList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "KA-Nonce", scope = AgreementMethodType.class)
    public JAXBElement<byte[]> createAgreementMethodTypeKANonce(byte[] value) {
        return new JAXBElement<byte[]>(_AgreementMethodTypeKANonce_QNAME, byte[].class, AgreementMethodType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "OriginatorKeyInfo", scope = AgreementMethodType.class)
    public JAXBElement<KeyInfoType> createAgreementMethodTypeOriginatorKeyInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_AgreementMethodTypeOriginatorKeyInfo_QNAME, KeyInfoType.class, AgreementMethodType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/04/xmlenc#", name = "RecipientKeyInfo", scope = AgreementMethodType.class)
    public JAXBElement<KeyInfoType> createAgreementMethodTypeRecipientKeyInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_AgreementMethodTypeRecipientKeyInfo_QNAME, KeyInfoType.class, AgreementMethodType.class, value);
    }

}
